# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://itsFatlumSMP.github.io"
baseurl: "/itsFatlumSMP.github.io"
siteIcon: /media/itsFatlumSMPIcon.png
siteYear: 2024
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: itsFatlum SMP
serverDescription: Fatlum's official Minecraft SMP server!
serverIP: fatlum.aternos.me
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/6wqrGkRqHz
discordServerID: 1203001257858441216
discordChannelID: 1295746909276868699


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/